export enum TOOL_LINKS {
    JS = 'https://www.ecma-international.org/publications-and-standards/standards/ecma-262/',
    ANTD = 'https://ant.design/',
    HTML = 'https://html.spec.whatwg.org/multipage/',
    SC = 'https://styled-components.com/',
    MUI = 'https://mui.com/',
    CSS_MODULES = 'https://github.com/css-modules/css-modules',
    REACT = 'https://reactjs.org',
    PREACT = 'https://preactjs.com/',
    GIT = 'https://git-scm.com/',
    TS = 'https://www.typescriptlang.org/',
    NEXT = 'https://nextjs.org/',
    JQUERY = 'https://jquery.com/',
    FIGMA = 'https://www.figma.com/',
    CSS = 'https://w3.org/Style/CSS/',
    BEM = 'https://bem.info/methodology/',
    NPM = 'https://www.npmjs.com/',
    REDUX = 'https://redux.js.org/',
    NODE = 'https://nodejs.org/en/',
    EFFECTOR = 'https://effector.dev/',
    ETHERS = 'https://docs.ethers.org/v5/',
    SASS = 'https://sass-lang.com/'
}